### ISSUE TITLE
(API) Database connection leak

### ISSUE THREAD

**Issue by SakuraIsayeki** [SakuraIsayeki/WoWS-Karma#46]
For now several weeks, APIs have been hit with a Connection leak issue, that has been grinding all DB-related requests down to a dead halt once a leak has hit all available connections of a pool.

After a moment, this type of Exception gets thrown: 
```
[03:12:22 ERR] Connection id "0HMBHR8BBDTFA", Request id "0HMBHR8BBDTFA:00000002": An unhandled exception was thrown by the application.
Microsoft.EntityFrameworkCore.Storage.RetryLimitExceededException: The maximum number of retries (6) was exceeded while executing database operations with 'NpgsqlRetryingExecutionStrategy'. See the inner exception for the most recent failure.
 ---> Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise 'Max Pool Size' (currently 100) or 'Timeout' (currently 15 seconds) in your connection string.
 ---> System.TimeoutException: The operation has timed out.
   at Npgsql.ConnectorPool.<Get>g__RentAsync|29_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass28_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at WowsKarma.Common.Models.DTOs.AccountKarmaDTO.ToDictionary(IEnumerable`1 values) in D:\Code\Source\WoWS-Karma\WowsKarma.Common\Models\DTOs\AccountKarmaDTO.cs:line 13
   at WowsKarma.Api.Controllers.PlayerController.FetchKarmas(UInt32[] ids) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Controllers\PlayerController.cs:line 56
   at lambda_method116(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WowsKarma.Api.Middlewares.RequestLoggingMiddleware.Invoke(HttpContext context) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Middlewares\RequestLoggingMiddleware.cs:line 52
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[03:12:23 ERR] An error occurred using the connection to database 'WowsKarma-Api-NA' on server ''.
```

Several fixes have been deployed to attempt issue mitigation, but in vain. The only clearance that this issue has is periodic restarts of an API by affected region.

Issue must be fixed ASAP, however no root cause has been found, as of yet.

**Comment by SakuraIsayeki** [comment]
After extensive load testing (methods inspired from @stewieoO), we've determined that the Posts page (https://wows-karma.com/Posts) is hit with a severe leak. 
Indeed, one page hit loads one dedicated connection to the Database, as the SignalR hub is being requested. However, the DB connection doesn't get closed or reused once the SignalR connection ends, meaning that the DB connection is lost forever to its Pool.

**Comment by SakuraIsayeki** [comment]
Hotfix has been deployed to the API, on commit 432b949, that mitigates DB connection leaks through better lifetime management.
Will be monitoring the situation closely or the next few days.

**Comment by SakuraIsayeki** [comment]
Issue has been deemed viably fixed, as no connection leaks have manifested since the fix was shadow-released on API.

Many thanks to @AdmiralSnyder, @stewieoO, @VelvetThePanda, and @nathanielboucher for helping diagnose and fix this long-standing issue.
