### ISSUE TITLE
Cant upload replays

### ISSUE THREAD

**Issue by GitHubRly** [SakuraIsayeki/WOWS-Karma#76]
16/03/22 11:48
![image](https://user-images.githubusercontent.com/101707412/158562877-e138452d-7555-4af4-8cd2-c162f45132ee.png)

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WowsKarma.Web.Services.PostService.SubmitNewPostAsync(PlayerPostDTO post, IBrowserFile replayFile, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Web\Services\PostService.cs:line 105
   at WowsKarma.Web.Pages.Posts.EditorModal.ModalSubmitAsync() in D:\Code\Source\WoWS-Karma\WowsKarma.Web\Pages\Posts\EditorModal.razor:line 162
```

**Comment by SakuraIsayeki** [comment]
Related to #75

**Comment by SakuraIsayeki** [comment]
Fixed as cascade with commit bc328da6729183491ce85609d58246e14d894f70.
