### ISSUE TITLE
Unable to open clan page 

### ISSUE THREAD

**Issue by K-Bomb** [SakuraIsayeki/WOWS-Karma#77]
Unable to open Krama page for -WD-
https://na.wows-karma.com/clan/1000081551,-WD--Well%20Done!
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WowsKarma.Web.Services.ClanService.FetchClanProfileFullAsync(UInt32 id) in D:\Code\Source\WoWS-Karma\WowsKarma.Web\Services\ClanService.cs:line 39
   at WowsKarma.Web.Pages.Clans.ClanView.OnParametersSetAsync() in D:\Code\Source\WoWS-Karma\WowsKarma.Web\Pages\Clans\ClanView.razor:line 134
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Also unable to log in. Creating separate issue for that.

**Comment by SakuraIsayeki** [comment]
issue is linked to clan name, starting with a special character. 
Indeed it seems that clans starting with a dash (An example on EU: https://wows-karma.com/clan/500200698,-TWA--All%20your%20base%20are%20belong%20to%20us/) will induce ID parsing into error, and force it to 0.

No API fix should be needed for this issue.
